
version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: blocks
      POSTGRES_USER: blocks
      POSTGRES_DB: blocks
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
