version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/remoteview/service-blocks
    steps:
      - checkout
      - run: make dev-dependencies
      - run: go mod download
      - run: make coverage.coveralls

