// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-05-28 15:25:36.736555942 -0700 PDT m=+0.053869559

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Get block",
        "title": "Blocks api",
        "contact": {
            "name": "Ivan Santos",
            "url": "https://ivansantos.me",
            "email": "pingme@ivansantos.me"
        },
        "license": {},
        "version": "1.0"
    },
    "host": "localhost:3000",
    "basePath": "/",
    "paths": {
        "/_health": {
            "get": {
                "description": "Health check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Health check"
            }
        },
        "/blocks": {
            "get": {
                "description": "List blocks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "List blocks"
            }
        },
        "/blocks/{id}": {
            "get": {
                "description": "Get block",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get block"
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
